name: Ping Flask App Action

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping your Flask App
        run: curl -s -o /dev/null -w "%{http_code}" https://event-application-site.onrender.com/heartbeat